default_agent: my_mcp_server
agents:
  my_mcp_server:
    name: my_mcp_server
    entrypoint: /Users/sohamgokulamrutkar/Desktop/AWS_Cost/my_mcp_server.py
    deployment_type: direct_code_deploy
    runtime_type: PYTHON_3_11
    platform: linux/arm64
    container_runtime: null
    source_path: /Users/sohamgokulamrutkar/Desktop/AWS_Cost
    aws:
      execution_role: arn:aws:iam::989064033484:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-cb7bbfb8e9
      execution_role_auto_create: false
      account: '989064033484'
      region: us-east-1
      ecr_repository: null
      ecr_auto_create: false
      s3_path: s3://bedrock-agentcore-codebuild-sources-989064033484-us-east-1
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: MCP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: my_mcp_server-mMJfzBHU1w
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:989064033484:runtime/my_mcp_server-mMJfzBHU1w
      agent_session_id: 47c30f5a-9f72-4e41-9fd9-975004ed7726
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: STM_ONLY
      memory_id: my_mcp_server_mem-SEnTfzA26t
      memory_arn: arn:aws:bedrock-agentcore:us-east-1:989064033484:memory/my_mcp_server_mem-SEnTfzA26t
      memory_name: my_mcp_server_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
